In [6]:
import numpy as np
from scipy import stats
import scipy.stats
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest

In [8]:
ds_mycars = pd.read_csv("./mycars.csv")
ds_mycars.head()

,manufacturer,model,displacement,year,cylinder,automatic,driving,mpg,highway_mileage,fuel,class
0,audi,a4,1.8,1999,4,auto,f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual,f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual,f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto,f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto,f,16,26,p,compact

In [11]:
df = ds_mycars[['model','mpg']]
df.groupby('model').describe()

                         mpg                                                 \
                       count       mean       std   min    25%   50%    75%
model
4runner 4wd              6.0  15.166667  0.752773  14.0  15.00  15.0  15.75
a4                       7.0  18.857143  1.864454  16.0  18.00  18.0  20.50
a4 quattro               8.0  17.125000  1.807722  15.0  15.75  17.0  18.25
a6 quattro               3.0  16.000000  1.000000  15.0  15.50  16.0  16.50
altima                   6.0  20.666667  1.966384  19.0  19.00  20.0  22.50
c1500 suburban 2wd       5.0  12.800000  1.303840  11.0  12.00  13.0  14.00
camry                    7.0  19.857143  1.463850  18.0  18.50  21.0  21.00
camry solara             7.0  19.857143  1.772811  18.0  18.00  21.0  21.00
caravan 2wd             11.0  15.818182  1.834022  11.0  15.50  16.0  17.00
civic                    9.0  24.444444  1.943651  21.0  24.00  24.0  25.00
corolla                  5.0  25.600000  1.673320  24.0  24.00  26.0  26.00
corvette                 5.0  15.400000  0.547723  15.0  15.00  15.0  16.00
dakota pickup 4wd        9.0  12.777778  1.986063   9.0  11.00  14.0  14.00
durango 4wd              7.0  11.857143  1.573592   9.0  11.00  13.0  13.00
expedition 2wd           3.0  11.333333  0.577350  11.0  11.00  11.0  11.50
explorer 4wd             6.0  13.666667  0.816497  13.0  13.00  13.5  14.00
f150 pickup 4wd          7.0  13.000000  1.000000  11.0  13.00  13.0  13.50
forester awd             6.0  18.833333  0.983192  18.0  18.00  18.5  19.75
grand cherokee 4wd       8.0  13.500000  2.507133   9.0  12.50  14.0  15.00
grand prix               5.0  17.000000  1.000000  16.0  16.00  17.0  18.00
gti                      5.0  20.000000  2.000000  17.0  19.00  21.0  21.00
impreza awd              8.0  19.625000  0.744024  19.0  19.00  19.5  20.00
jetta                    9.0  21.222222  4.867694  16.0  19.00  21.0  21.00
k1500 tahoe 4wd          4.0  12.500000  1.732051  11.0  11.00  12.5  14.00
land cruiser wagon 4wd   2.0  12.000000  1.414214  11.0  11.50  12.0  12.50
malibu                   5.0  18.800000  1.923538  17.0  18.00  18.0  19.00
maxima                   3.0  18.666667  0.577350  18.0  18.50  19.0  19.00
mountaineer 4wd          4.0  13.250000  0.500000  13.0  13.00  13.0  13.25
mustang                  9.0  15.888889  1.452966  14.0  15.00  15.0  17.00
navigator 2wd            3.0  11.333333  0.577350  11.0  11.00  11.0  11.50
new beetle               6.0  24.000000  6.511528  19.0  20.00  20.5  27.00
passat                   7.0  18.571429  1.902379  16.0  17.50  18.0  20.00
pathfinder 4wd           4.0  13.750000  1.258306  12.0  13.50  14.0  14.25
ram 1500 pickup 4wd     10.0  11.400000  1.505545   9.0  11.00  11.5  12.75
range rover              4.0  11.500000  0.577350  11.0  11.00  11.5  12.00
sonata                   7.0  19.000000  1.414214  18.0  18.00  18.0  20.00
tiburon                  7.0  18.285714  1.603567  16.0  17.00  19.0  19.50
toyota tacoma 4wd        7.0  15.571429  0.786796  15.0  15.00  15.0  16.00


                         max
model
4runner 4wd             16.0
a4                      21.0
a4 quattro              20.0
a6 quattro              17.0
altima                  23.0
c1500 suburban 2wd      14.0
camry                   21.0
camry solara            22.0
caravan 2wd             18.0
civic                   28.0
corolla                 28.0
corvette                16.0
dakota pickup 4wd       15.0
durango 4wd             13.0
expedition 2wd          12.0
explorer 4wd            15.0
f150 pickup 4wd         14.0
forester awd            20.0
grand cherokee 4wd      17.0
grand prix              18.0
gti                     22.0
impreza awd             21.0
jetta                   33.0
k1500 tahoe 4wd         14.0
land cruiser wagon 4wd  13.0
malibu                  22.0
maxima                  19.0
mountaineer 4wd         14.0
mustang                 18.0
navigator 2wd           12.0
new beetle              35.0
passat                  21.0
pathfinder 4wd          15.0
ram 1500 pickup 4wd     13.0
range rover             12.0
sonata                  21.0
tiburon                 20.0
toyota tacoma 4wd       17.0

In [13]:
ds_Exh_QC1 = pd.read_csv('./Exh_QC1.csv')
df = ds_Exh_QC1[['Flaws', 'Period']]

count = df['Flaws'].value_counts().sort_index()

cumcnt = np.cumsum(count)
percent = count / sum(count) * 100
cumpct = np.cumsum(percent)

In [15]:
count_data = pd.DataFrame({'Count':count, 'CumCnt':cumcnt, 'Percent':percent,'CumPct':cumpct})
count_data.columns.name='Flaws'
count_data

count2 = df['Period'].value_counts().sort_index()
cumcnt2 = np.cumsum(count2)

percent2 = count2 / sum(count2) * 100
cumpct2 = np.cumsum(percent2)

count_data2 = pd.DataFrame({'Count':count2, 'CumCnt':cumcnt2, 'Percent':percent2, 'CumPct':cumpct2})
count_data2.columns.name='Period'

count_data2

Period   Count  CumCnt  Percent  CumPct
Day          7       7     17.5    17.5
Evening      7      14     17.5    35.0
Night       19      33     47.5    82.5
Weekend      7      40     17.5   100.0

In [17]:
mu = 115
sigma = 20
x = 135
prob = stats.norm.cdf(x, mu, sigma)
print("{0}분 이상 걸리는 A/S 작업 비율 {1:.1f}%".format(x, (1-prob)*100))

135분 이상 걸리는 A/S 작업 비율 15.9%

In [22]:
mu = 175
sigma = 5
x = 180
prob = stats.norm.cdf(x, mu, sigma)
print("키가 {0}cm일 경우, 속하는 비율 {1:.1f}%".format(x, (1-prob)*100))

키가 180cm일 경우, 속하는 비율 15.9%

In [23]:
mu = 12
sigma = 3
x1 = 15

prob1 = stats.norm.cdf(x1, mu, sigma)
print("{0}Km 이상 {1}Km 이하를 달릴 확률은 {2:.3f}에 해당함".format(mu, x1, (prob-0.5)))

12Km 이상 15Km 이하를 달릴 확률은 0.341에 해당함